name: release

on:
  release:
    types: [released ]
  workflow_dispatch:

jobs:
  release:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish_pure_python.yml@v1
    with:
      upload_to_pypi: ${{ (github.event_name == 'release') && (github.event.action == 'released') }}
    secrets:
      pypi_token: ${{ secrets.PYPI_PASSWORD_ASDF_MAINTAINER }}
